"""empty message

Revision ID: 1075c5bc38af
Revises: 0f40848fc255
Create Date: 2021-02-23 18:24:30.561105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1075c5bc38af'
down_revision = '0f40848fc255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_constraint('Artist_past_shows_fkey', 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'past_shows')
    op.drop_constraint('Venue_past_shows_fkey', 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'past_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Venue_past_shows_fkey', 'Venue', 'Shows', ['past_shows'], ['id'])
    op.add_column('Artist', sa.Column('past_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Artist_past_shows_fkey', 'Artist', 'Shows', ['past_shows'], ['id'])
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
