"""empty message

Revision ID: 3b14fbd3c66f
Revises: 1075c5bc38af
Create Date: 2021-02-23 23:45:10.796968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b14fbd3c66f'
down_revision = '1075c5bc38af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'name')
    # ### end Alembic commands ###
