"""empty message

Revision ID: 5c494657074f
Revises: 4f71968bcd22
Create Date: 2021-02-24 00:07:17.561328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c494657074f'
down_revision = '4f71968bcd22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['website'])
    op.create_unique_constraint(None, 'Artist', ['facebook_link'])
    op.create_unique_constraint(None, 'Artist', ['phone'])
    op.create_unique_constraint(None, 'Venue', ['facebook_link'])
    op.create_unique_constraint(None, 'Venue', ['address'])
    op.create_unique_constraint(None, 'Venue', ['website'])
    op.create_unique_constraint(None, 'Venue', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
